// Downloads Google Fonts (woff2) into ./fonts and writes ./fonts/fonts.css
// Usage: node tools/fetch-fonts.mjs
// All fonts used are SIL Open Font License (OFL) — safe to bundle.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')), '..');
const OUT = path.join(ROOT, 'fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext', 'vietnamese']);

// Every Japanese glyph the game uses (SFX, stand-stat labels). Keep in sync with js/ — tools/check-glyphs.mjs verifies.
const JP_TEXT = fs.readFileSync(path.join(ROOT, 'tools', 'jp-glyphs.txt'), 'utf8').replace(/\s+/g, '');

const FAMILIES = [
  { css: 'Dela+Gothic+One', as: 'Dela Gothic One', slug: 'dela' },
  { css: 'Bangers', as: 'Bangers', slug: 'bangers' },
  { css: 'Patrick+Hand', as: 'Patrick Hand', slug: 'patrick' },
  { css: 'Lora:ital,wght@0,400..700;1,400..700', as: 'Lora', slug: 'lora' },
  { css: 'Dela+Gothic+One', as: 'SFX JP', slug: 'sfxjp', text: JP_TEXT },
];

fs.mkdirSync(OUT, { recursive: true });
for (const f of fs.readdirSync(OUT)) if (f.endsWith('.woff2')) fs.unlinkSync(path.join(OUT, f));

let css = '/* Generated by tools/fetch-fonts.mjs — Google Fonts, SIL OFL 1.1 */\n';
for (const fam of FAMILIES) {
  let url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  if (fam.text) url += `&text=${encodeURIComponent(fam.text)}`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${fam.as}: HTTP ${res.status}`);
  const body = await res.text();
  // Split into blocks, each optionally preceded by a /* subset */ comment
  const re = /(?:\/\*\s*([^*]+?)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g;
  let m, n = 0;
  while ((m = re.exec(body))) {
    const subset = m[1] || (fam.text ? 'jp' : 'all');
    if (!fam.text && !KEEP.has(subset)) continue;
    const block = m[2];
    const src = /url\((https:[^)]+)\)/.exec(block)[1];
    const style = (/font-style:\s*(\w+)/.exec(block) || [, 'normal'])[1];
    const weight = (/font-weight:\s*([\d ]+);/.exec(block) || [, '400'])[1].trim();
    const range = /unicode-range:\s*([^;]+);/.exec(block);
    const file = `${fam.slug}-${weight.replace(' ', '_')}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT, file), buf);
    css += `@font-face{font-family:'${fam.as}';font-style:${style};font-weight:${weight};font-display:block;` +
      `src:url(${file}) format('woff2');${range ? `unicode-range:${range[1]};` : ''}}\n`;
    n++;
    console.log(`  ${file}  ${(buf.length / 1024).toFixed(1)} KB`);
  }
  console.log(`${fam.as}: ${n} face(s)`);
}
fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
console.log('wrote fonts/fonts.css');
